default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  uername: sakura_market
  pass: sakura_market

development:
  <<: *default
  database: sakura_market_development

test:
  <<: *default
  database: sakura_market_test

production:
  <<: *default
  database: sample-market-production 
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

